# Generated by Django 5.2.12 on 2026-03-28 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('rent', 'Rent'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('bills', 'Bills & Utilities'), ('health', 'Healthcare'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelancing'), ('business', 'Business'), ('investment', 'Investment'), ('gift', 'Gift'), ('other', 'Other')], max_length=50),
        ),
    ]
